### ISSUE TITLE
User pages don't show titles of posts the user have commented in

### ISSUE THREAD

**Issue by DoomTay** [notabugio-archived/notabug-ui#48]
The only way to know what thread the comment was in is through the "permalink" link

**Comment by go1dfish** [comment]
Thanks for the report, this is a more general issue with user pages (often your own user page wont load at all now) It's an issue somewhere in the chaingun client and I plan to dig into it more once server-1.0 is ready

**Comment by go1dfish** [comment]
This should be fixed now

**Comment by DoomTay** [comment]
How long would it take for changes to take effect? Because I'm still seeing a lack of titles.

https://i.imgur.com/C7LhBAl.png

**Comment by go1dfish** [comment]
Oh that’s a different app entirely.

https://github.com/snew/snew

Will keep that in mind next time I update it but will probably be a while.

This repo is for https://notabug.io which is a federated alternative to reddit that doesn’t use Reddit’s content at all.
